listen=YES
listen_ipv6=NO

anonymous_enable=NO

local_enable=YES
write_enable=NO

local_umask=022

dirmessage_enable=YES
use_localtime=YES

xferlog_enable=YES
connect_from_port_20=YES

chroot_local_user=YES

user_sub_token=$USER
local_root=/var/log/devops-scenario

pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010
pasv_address=192.168.36.129
