module(load="imudp")
module(load="omkafka")

template(
    name="DevOpsLog"
    type="string"
    string="%rawmsg%\n"
)

ruleset(name="devops_udp") {

    action(
        type="omfile"
        file="/var/log/devops-scenario/devops.log"
        template="DevOpsLog"
    )

    action(
        type="omkafka"
        broker=["192.168.36.129:9092"]
        topic="devops-logs"
        template="DevOpsLog"
        partitions.auto="on"
        resubmitOnFailure="on"
    )
}

input(
    type="imudp"
    port="5514"
    ruleset="devops_udp"
)
